// <auto-generated />
using System;
using Fucha.DataLayer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fucha.DataLayer.Migrations
{
    [DbContext(typeof(FuchaMilkteaContext))]
    [Migration("20221123061632_I1")]
    partial class I1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Fucha.DomainClasses.AddOn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("AddOnPrice")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AddOns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddOnPrice = 10.0,
                            Name = "Pearl"
                        },
                        new
                        {
                            Id = 2,
                            AddOnPrice = 10.0,
                            Name = "Nata"
                        },
                        new
                        {
                            Id = 3,
                            AddOnPrice = 10.0,
                            Name = "Nutella"
                        },
                        new
                        {
                            Id = 4,
                            AddOnPrice = 10.0,
                            Name = "Cookies"
                        },
                        new
                        {
                            Id = 5,
                            AddOnPrice = 10.0,
                            Name = "Cream Cheese"
                        });
                });

            modelBuilder.Entity("Fucha.DomainClasses.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("MenuCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MenuCategoryId = 1,
                            Name = "Okinawa"
                        },
                        new
                        {
                            Id = 2,
                            MenuCategoryId = 1,
                            Name = "Red Velvet"
                        },
                        new
                        {
                            Id = 3,
                            MenuCategoryId = 1,
                            Name = "Wintermelon"
                        },
                        new
                        {
                            Id = 4,
                            MenuCategoryId = 1,
                            Name = "Salted Caramel"
                        },
                        new
                        {
                            Id = 5,
                            MenuCategoryId = 1,
                            Name = "Taro"
                        },
                        new
                        {
                            Id = 6,
                            MenuCategoryId = 2,
                            Name = "Cookies & Cream"
                        },
                        new
                        {
                            Id = 7,
                            MenuCategoryId = 2,
                            Name = "Dark Chocolate"
                        },
                        new
                        {
                            Id = 8,
                            MenuCategoryId = 2,
                            Name = "Hokkaido"
                        },
                        new
                        {
                            Id = 9,
                            MenuCategoryId = 2,
                            Name = "Black Wintermel"
                        },
                        new
                        {
                            Id = 10,
                            MenuCategoryId = 2,
                            Name = "Avocado Cheescake"
                        },
                        new
                        {
                            Id = 11,
                            MenuCategoryId = 2,
                            Name = "Choco Bunny"
                        },
                        new
                        {
                            Id = 12,
                            MenuCategoryId = 2,
                            Name = "Choco Berry Meiji"
                        },
                        new
                        {
                            Id = 13,
                            MenuCategoryId = 2,
                            Name = "Mango Graham Cabin"
                        },
                        new
                        {
                            Id = 14,
                            MenuCategoryId = 2,
                            Name = "Salty Cream Okinawa"
                        },
                        new
                        {
                            Id = 15,
                            MenuCategoryId = 3,
                            Name = "Japanese Sausage with Rice & Egg"
                        },
                        new
                        {
                            Id = 16,
                            MenuCategoryId = 3,
                            Name = "Hungarian Sausage with Rice & Egg"
                        },
                        new
                        {
                            Id = 17,
                            MenuCategoryId = 3,
                            Name = "Spam Bacon with Rice & Egg"
                        },
                        new
                        {
                            Id = 18,
                            MenuCategoryId = 3,
                            Name = "Cheesedog with Rice & Hotdog"
                        },
                        new
                        {
                            Id = 19,
                            MenuCategoryId = 3,
                            Name = "Hungarian Sausage"
                        },
                        new
                        {
                            Id = 20,
                            MenuCategoryId = 3,
                            Name = "Spam & Japanese Sausage"
                        },
                        new
                        {
                            Id = 21,
                            MenuCategoryId = 6,
                            Name = "Hungarian Solo"
                        },
                        new
                        {
                            Id = 22,
                            MenuCategoryId = 6,
                            Name = "Assorted Balls"
                        },
                        new
                        {
                            Id = 23,
                            MenuCategoryId = 6,
                            Name = "Gyoza"
                        },
                        new
                        {
                            Id = 24,
                            MenuCategoryId = 6,
                            Name = "Fries"
                        },
                        new
                        {
                            Id = 25,
                            MenuCategoryId = 6,
                            Name = "Siomai"
                        },
                        new
                        {
                            Id = 41,
                            MenuCategoryId = 4,
                            Name = "Cheesy Garlic"
                        },
                        new
                        {
                            Id = 42,
                            MenuCategoryId = 4,
                            Name = "Ham 'N Cheese"
                        },
                        new
                        {
                            Id = 43,
                            MenuCategoryId = 4,
                            Name = "Peperoni"
                        },
                        new
                        {
                            Id = 44,
                            MenuCategoryId = 4,
                            Name = "Hawaiian"
                        },
                        new
                        {
                            Id = 45,
                            MenuCategoryId = 4,
                            Name = "Beef Mushroom"
                        });
                });

            modelBuilder.Entity("Fucha.DomainClasses.MenuCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MenuCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Classic Milk Tea"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Premium Milk Tea"
                        },
                        new
                        {
                            Id = 3,
                            Name = "All Day Meals"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Pizza Regular"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Pizza Premium"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Snacks"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Ala Carte"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Chicken Wings"
                        });
                });

            modelBuilder.Entity("Fucha.DomainClasses.MenuPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("MenuCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("MenuId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("SizeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MenuPrices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MenuCategoryId = 1,
                            Price = 50.0,
                            SizeId = 1
                        },
                        new
                        {
                            Id = 2,
                            MenuCategoryId = 1,
                            Price = 60.0,
                            SizeId = 2
                        },
                        new
                        {
                            Id = 3,
                            MenuCategoryId = 1,
                            Price = 70.0,
                            SizeId = 3
                        },
                        new
                        {
                            Id = 4,
                            MenuCategoryId = 1,
                            Price = 120.0,
                            SizeId = 4
                        },
                        new
                        {
                            Id = 5,
                            MenuCategoryId = 2,
                            Price = 70.0,
                            SizeId = 2
                        },
                        new
                        {
                            Id = 6,
                            MenuCategoryId = 2,
                            Price = 90.0,
                            SizeId = 3
                        },
                        new
                        {
                            Id = 7,
                            MenuCategoryId = 2,
                            Price = 130.0,
                            SizeId = 4
                        },
                        new
                        {
                            Id = 8,
                            MenuCategoryId = 3,
                            MenuId = 15,
                            Price = 60.0
                        },
                        new
                        {
                            Id = 9,
                            MenuCategoryId = 3,
                            MenuId = 16,
                            Price = 75.0
                        },
                        new
                        {
                            Id = 10,
                            MenuCategoryId = 3,
                            MenuId = 17,
                            Price = 65.0
                        },
                        new
                        {
                            Id = 11,
                            MenuCategoryId = 3,
                            MenuId = 18,
                            Price = 65.0
                        },
                        new
                        {
                            Id = 12,
                            MenuCategoryId = 3,
                            MenuId = 19,
                            Price = 50.0
                        },
                        new
                        {
                            Id = 13,
                            MenuCategoryId = 3,
                            MenuId = 20,
                            Price = 65.0
                        },
                        new
                        {
                            Id = 14,
                            MenuCategoryId = 6,
                            MenuId = 21,
                            Price = 50.0
                        },
                        new
                        {
                            Id = 15,
                            MenuCategoryId = 6,
                            MenuId = 22,
                            Price = 25.0
                        },
                        new
                        {
                            Id = 16,
                            MenuCategoryId = 6,
                            MenuId = 23,
                            Price = 40.0
                        },
                        new
                        {
                            Id = 17,
                            MenuCategoryId = 6,
                            MenuId = 24,
                            Price = 30.0
                        },
                        new
                        {
                            Id = 18,
                            MenuCategoryId = 6,
                            MenuId = 25,
                            Price = 25.0
                        },
                        new
                        {
                            Id = 19,
                            MenuCategoryId = 4,
                            MenuId = 41,
                            Price = 115.0
                        },
                        new
                        {
                            Id = 20,
                            MenuCategoryId = 4,
                            MenuId = 42,
                            Price = 115.0
                        },
                        new
                        {
                            Id = 21,
                            MenuCategoryId = 4,
                            MenuId = 43,
                            Price = 115.0
                        },
                        new
                        {
                            Id = 22,
                            MenuCategoryId = 4,
                            MenuId = 44,
                            Price = 115.0
                        },
                        new
                        {
                            Id = 23,
                            MenuCategoryId = 4,
                            MenuId = 45,
                            Price = 115.0
                        });
                });

            modelBuilder.Entity("Fucha.DomainClasses.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AddOn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("AddOnPrice")
                        .HasColumnType("float");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Fucha.DomainClasses.PORecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("DatePurchased")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Measure")
                        .HasColumnType("float");

                    b.Property<int>("MeasurementUnit")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("PurchaseRecordId")
                        .HasColumnType("int");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PORecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            DatePurchased = "Wednesday, 23 November 2022",
                            Measure = 100.0,
                            MeasurementUnit = 1,
                            Price = 100.0,
                            PurchaseRecordId = 1,
                            StockId = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            DatePurchased = "Wednesday, 23 November 2022",
                            Measure = 50.0,
                            MeasurementUnit = 1,
                            Price = 50.0,
                            PurchaseRecordId = 1,
                            StockId = 2
                        },
                        new
                        {
                            Id = 3,
                            Category = 1,
                            DatePurchased = "Wednesday, 23 November 2022",
                            Measure = 50.0,
                            MeasurementUnit = 1,
                            Price = 50.0,
                            PurchaseRecordId = 2,
                            StockId = 4
                        });
                });

            modelBuilder.Entity("Fucha.DomainClasses.PurchaseRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DatePurchased")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemQuantity")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PurchaseRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DatePurchased = "Wednesday, 23 November 2022",
                            ItemQuantity = 2,
                            SupplierId = 1,
                            TotalAmount = 100.0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            DatePurchased = "Wednesday, 23 November 2022",
                            ItemQuantity = 1,
                            SupplierId = 3,
                            TotalAmount = 50.0,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Fucha.DomainClasses.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AddOnId")
                        .HasColumnType("int");

                    b.Property<int>("MeasurementUnit")
                        .HasColumnType("int");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<double>("RequiredMeasure")
                        .HasColumnType("float");

                    b.Property<int?>("SizeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 31,
                            MeasurementUnit = 3,
                            MenuId = 41,
                            RequiredMeasure = 1.0
                        },
                        new
                        {
                            Id = 32,
                            MeasurementUnit = 3,
                            MenuId = 42,
                            RequiredMeasure = 1.0
                        },
                        new
                        {
                            Id = 33,
                            MeasurementUnit = 3,
                            MenuId = 43,
                            RequiredMeasure = 1.0
                        },
                        new
                        {
                            Id = 34,
                            MeasurementUnit = 3,
                            MenuId = 44,
                            RequiredMeasure = 1.0
                        },
                        new
                        {
                            Id = 35,
                            MeasurementUnit = 3,
                            MenuId = 45,
                            RequiredMeasure = 1.0
                        });
                });

            modelBuilder.Entity("Fucha.DomainClasses.SaleTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DateSold")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemQuantity")
                        .HasColumnType("int");

                    b.Property<double>("TotalSales")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SalesTransaction");
                });

            modelBuilder.Entity("Fucha.DomainClasses.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sizes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Small"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Large"
                        },
                        new
                        {
                            Id = 4,
                            Name = "1 Liter"
                        });
                });

            modelBuilder.Entity("Fucha.DomainClasses.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AddOnId")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("DateAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<string>("LastRestocked")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Measure")
                        .HasColumnType("float");

                    b.Property<int>("MeasurementUnit")
                        .HasColumnType("int");

                    b.Property<int?>("MenuId")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            IsRemoved = false,
                            Measure = 5.0,
                            MeasurementUnit = 1,
                            MenuId = 1,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            IsRemoved = false,
                            Measure = 5.0,
                            MeasurementUnit = 1,
                            MenuId = 2,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 3,
                            Category = 0,
                            IsRemoved = false,
                            Measure = 5.0,
                            MeasurementUnit = 1,
                            MenuId = 3,
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 10,
                            AddOnId = 3,
                            Category = 1,
                            IsRemoved = false,
                            Measure = 5.0,
                            MeasurementUnit = 0,
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 41,
                            Category = 2,
                            IsRemoved = false,
                            Measure = 100.0,
                            MeasurementUnit = 3,
                            MenuId = 41,
                            SupplierId = 10
                        },
                        new
                        {
                            Id = 42,
                            Category = 2,
                            IsRemoved = false,
                            Measure = 100.0,
                            MeasurementUnit = 3,
                            MenuId = 42,
                            SupplierId = 10
                        },
                        new
                        {
                            Id = 43,
                            Category = 2,
                            IsRemoved = false,
                            Measure = 100.0,
                            MeasurementUnit = 3,
                            MenuId = 43,
                            SupplierId = 10
                        },
                        new
                        {
                            Id = 44,
                            Category = 2,
                            IsRemoved = false,
                            Measure = 100.0,
                            MeasurementUnit = 3,
                            MenuId = 44,
                            SupplierId = 10
                        },
                        new
                        {
                            Id = 45,
                            Category = 2,
                            IsRemoved = false,
                            Measure = 100.0,
                            MeasurementUnit = 3,
                            MenuId = 45,
                            SupplierId = 10
                        });
                });

            modelBuilder.Entity("Fucha.DomainClasses.StockCategorys", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("MeasurementUnit")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StockCategories");
                });

            modelBuilder.Entity("Fucha.DomainClasses.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ContactNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("DateAdded")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "157 Josefa Drive Brgy, Corazon De Jesus, San Juan City",
                            ContactNumber = 9178077279L,
                            DateAdded = "Wednesday, 23 November 2022",
                            Name = "In joy"
                        },
                        new
                        {
                            Id = 2,
                            Address = "208A Banawe St., Brgy Tatalon, Quezon City",
                            ContactNumber = 9175858100L,
                            DateAdded = "Wednesday, 23 November 2022",
                            Name = "PHNI Bubble Tea Store"
                        },
                        new
                        {
                            Id = 3,
                            Address = "San Juan Manila",
                            ContactNumber = 9171284151L,
                            DateAdded = "Wednesday, 23 November 2022",
                            Name = "MSCS PrimeGoods, Inc."
                        },
                        new
                        {
                            Id = 10,
                            Address = "#24 F Pasco Aveue Santolan, Pasig, Philippines",
                            ContactNumber = 9955823086L,
                            DateAdded = "Wednesday, 23 November 2022",
                            Name = "Pizza Crust"
                        });
                });

            modelBuilder.Entity("Fucha.DomainClasses.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DateCreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isRemoved")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Roy",
                            LastName = "Sabenecio",
                            Password = "r",
                            Role = "Admin",
                            UserName = "r",
                            UserStatus = "Approved",
                            isRemoved = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
